### ISSUE TITLE
Unable to load library

### ISSUE THREAD

**Issue by RAJESH-TECHMILEAGE** [frett27/jfgdb#2]
hi Patrice Freydiere,
             when i try to run the CRUDExample.java it is calling SharedLibrariesInitializer class initLibraries method, there it is trying load loadingDll file using this NativeLibrary.getInstance(loadingDll); method we are getting below issue.

![capture](https://cloud.githubusercontent.com/assets/12729282/20751555/6116f738-b722-11e6-8e1f-98e9bd5133ee.PNG)

**Comment by frett27** [comment]
Hi Rajesh, can you double check you have installed the VC++ 2012 redist C++, this is a requierment, 
There are VC++ dependent DLLS needed for the FileGDBAPI, 
i doubled checked the given maven repository and it works fine for me.

https://github.com/Esri/file-geodatabase-api


Patrice

**Comment by frett27** [comment]
VC++ redist package http://assiste.com/Visual_C++_Packages_redistribuables.html
take x64 (only x64 supported in this dependency), and 2012 one
