### ISSUE TITLE
issue with project root structure 

### ISSUE THREAD

**Issue by RAJESH-TECHMILEAGE** [frett27/jfgdb#3]
Hi Patrice Freydiere,
           i am running this gradle  project on windows 7  64 bit environment, when i use gradle import and and try to build the project i am getting below project root structure
![image](https://cloud.githubusercontent.com/assets/12729282/20915875/94e69362-bbae-11e6-8e66-ea07b567b568.png)

 when i refer the code  in jfgdb project build.gradle file it is trying to fetch fGDBJNIWrapperSharedLibrary from /nativewrapper/build/binaries and copying it in to output directory,but i am unable to see that folder in my native wrapper project root structure, can you please help me to resolve on this issue , 
![image](https://cloud.githubusercontent.com/assets/12729282/20915468/1b540a90-bbac-11e6-8fbd-6d54ff9fae31.png)

**Comment by frett27** [comment]
Hi Rajesh, 
have you tried the 
gradlew build -x test ? mentionned on the README ?


C:\tmp\jfgdb>set ESRI_FILE_GDB_HOME=C:\projets\FILEGEODATABASE_BINARIES\FileGDB_API_VS2012_1_4

C:\tmp\jfgdb>c:\java\setenv7.cmd

C:\tmp\jfgdb>set JAVA_HOME=C:\Java\jdk1.7.0_01

C:\tmp\jfgdb>path C:\Java\jdk1.7.0_01\bin;C:\OCaml\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Broadcom\Broadcom 802.11;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Hewlett-Packard\SimplePass\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\scala\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\nodejs\;C:\Go\bin;C:\Users\use\AppData\Local\Programs\Python\Launcher\;C:\GNAT\2014\bin;C:\Users\use\AppData\Local\atom\bin;C:\Users\use\AppData\Roaming\npm;C:\Users\use\AppData\Local\Pandoc\;C:\Users\use\AppData\Local\Microsoft\WindowsApps;

C:\tmp\jfgdb>gradlew build -x test
Output libs dir :C:\tmp\jfgdb\jfgdb\build\resources\main\sharedlibraries\0.1.4.1-SNAPSHOT\win32-x86-64
access key read
:jfgdb:copySharedLibsInResources
:jfgdb:createVersionPropertyFile
:nativewrapper:distTar UP-TO-DATE
:nativewrapper:distZip UP-TO-DATE
:nativewrapper:compileFGDBJNIWrapperSharedLibraryFGDBJNIWrapperCpp
:nativewrapper:linkFGDBJNIWrapperSharedLibrary
:nativewrapper:fGDBJNIWrapperSharedLibrary
:nativewrapper:compileFGDBJNIWrapperStaticLibraryFGDBJNIWrapperCpp
:nativewrapper:createFGDBJNIWrapperStaticLibrary
:nativewrapper:fGDBJNIWrapperStaticLibrary
:nativewrapper:compileJava UP-TO-DATE
:nativewrapper:processResources UP-TO-DATE
:nativewrapper:classes UP-TO-DATE
:nativewrapper:jar
:nativewrapper:assemble
:nativewrapper:check
:nativewrapper:build
:jfgdb:compileJava
:jfgdb:transfertPreparedBinaries
downloading .
:jfgdb:processResources
:jfgdb:classes
:jfgdb:jar
:distTar
:distZip
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:assemble
:check
:build
:jfgdb:assemble
:jfgdb:check
:jfgdb:build

BUILD SUCCESSFUL

Total time: 28.862 secs

, once done, the folders are properly filled

![image](https://cloud.githubusercontent.com/assets/3824367/20942297/1cde8468-bbfb-11e6-89b7-dbeb6c1a3a42.png)

**Comment by RAJESH-TECHMILEAGE** [comment]
yes Patrice Freydiere,
          i used to build an application with gradlew build -x test command what you have  mentionned on the README file,also i tried what ever the steps you have given above screenshot in  my cmd even i am not getting binaries folder on my project root structure, i think i missed to install some of the required software for this project i dont know what i have missed

**when i build the project on command prompt:**


C:\temp\jfgdb>set ESRI_FILE_GDB_HOME=C:\projects\FILEGEODATABASE_BINARIES\filegd
b_api_vs2012_1_4

C:\temp\jfgdb>set JAVA_HOME=C:\Java\jdk1.7.0_51

C:\temp\jfgdb>path C:\Java\jdk1.7.0_51\bin;C:\Program Files (x86)\Intel\iCLS Cli
ent\;C:\Program Files\Intel\iCLS Client\;%SystemRoot%\system32;%SystemRoot%;%Sys
temRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program
Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Int
el(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Man
agement Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management E
ngine Components\IPT;E:\New folder\jboss-as-7.1.1.Final;C:\Program Files (x86)\S
kype\Phone

C:\temp\jfgdb>gradlew build -x test
Output libs dir :C:\temp\jfgdb\jfgdb\build\resources\main\sharedlibraries\0.1.4.
1-SNAPSHOT\win32-x86-64
access key read
:jfgdb:copySharedLibsInResources
:jfgdb:createVersionPropertyFile
:nativewrapper:distTar UP-TO-DATE
:nativewrapper:distZip UP-TO-DATE
:nativewrapper:compileJava UP-TO-DATE
:nativewrapper:processResources UP-TO-DATE
:nativewrapper:classes UP-TO-DATE
:nativewrapper:jar UP-TO-DATE
:nativewrapper:assemble
:nativewrapper:check
:nativewrapper:build
:jfgdb:compileJava UP-TO-DATE
:jfgdb:transfertPreparedBinaries
downloading .
:jfgdb:processResources
:jfgdb:classes
:jfgdb:jar UP-TO-DATE
:distTar UP-TO-DATE
:distZip UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:assemble UP-TO-DATE
:check
:build
:jfgdb:assemble UP-TO-DATE
:jfgdb:check
:jfgdb:build

BUILD SUCCESSFUL

Total time: 9.018 secs
C:\temp\jfgdb>

**Project RootStructure:**

![image](https://cloud.githubusercontent.com/assets/12729282/20965427/a163f934-bc9b-11e6-9424-4b7e5ef1c6cd.png)



 **ESRI_FILE_GDB_HOME  ** 
path:C:\projects\FILEGEODATABASE_BINARIES\filegdb_api_vs2012_1_4 

**filegdb_api_vs2012_1_4  contains**

![image](https://cloud.githubusercontent.com/assets/12729282/20967245/6ed1f9f4-bca4-11e6-8597-041c70791e2b.png)

**Comment by frett27** [comment]
Hi it seems the native compiler task don't find the VC++ compiler, 
tasks associated to binaries are not launched in your case.

do you have it installed on the computer ? if you want to compile it on computer rather than use the jar (that embedded the DLLs)

you might use 2012 version to be compatible with the FGDBAPI.

**Comment by frett27** [comment]
think this is an environment issue, closing it
