### ISSUE TITLE
"cannot open shared object file: No such file or directory "in ubuntu 16.4

### ISSUE THREAD

**Issue by 553226713** [frett27/jfgdb#4]
hello,i used it in ubuntu16.4,but when i call the initLibraries() method,it throw a exception whih "
/tmp/fgdbsharedlibs/0.1.4/libFGDBJNIWrapper.so: libFileGDBAPI.so: cannot open shared object file: No such file or directory".
 but i check the floder " /tmp/fgdbsharedlibs/0.1.4",it's existd.
thanks.

**Comment by frett27** [comment]
As Linux does not support changing dynamic executable path on dlopen. You
need to set the LD_LIBRARY_PATH to the tmp folder before launching.

This is mentioned in the documentation.

There is probably a better way to do it. Or creating a shell script to do
it.


Patrice

**Comment by frett27** [comment]
yes ! thank's

you can also use the ldconfig if you want to separate the .so

https://linux.die.net/man/8/ldconfig
see : man ldconfig

Patrice

Le lun. 10 sept. 2018 à 03:21, 553226713 <notifications@github.com> a
écrit :
