### ISSUE TITLE
How to use it "as jdbc driver" in clients

### ISSUE THREAD

**Issue by adrianrb** [frett27/jfgdb#5]
Hello.

How to use this driver in client apps like DBeaver?

In DBeaver I can add custom drivers using sintax bellow, but I don´t know how fill some params (class, url):

```
<driver 
    id="jfgdb" 
    category="ESRI Filegeodatabase" 
    categories="embedded,file" 
    name="fGDB" 
    class="<main class?>" 
    url="jdbc:?" 
    description="JDBC driver for ESRI FGDB" 
    custom="true" 
    embedded="false" 
    anonymous="true">
        <library type="jar" path="D:\Desenv\jFGDB-driver\jfgdb-0.1.4.1-SNAPSHOT.jar" custom="true"/>
</driver>
```

Any help, pls?

Adrian

**Comment by frett27** [comment]
Jfgdb has no jdbc access yet. This might be implemented on to as far as the geometry type is properly defined.

**Comment by adrianrb** [comment]
> Jfgdb has no jdbc access yet. This might be implemented on to as far as the geometry type is properly defined.

Is there any plan to add it?
What you mean about "as far as the geometry type is properly defined"?
Your work **is very valuable**, and can be **further** if this option was added...

Adrian

**Comment by frett27** [comment]
Hi Adrian, and sorry for the late response delay, seems the notifications are not properly sets on my side,  

jdbc access is not planned on this repository, the aim on this repository is to provide a simple and efficient access to the native FGDB esri file format. So a building block for developing larger database access APIs. 

There are complementary jdbc building tools you can use to build jdbc access from this wrapper project ,  for example, the calcite apache project (used in phenix project for big data, and referenced in hortonworks distribution). there might be also some relevant alternatives projects to what you want to achieve (adding jdbc support on top of this project).  

fgdb is a geographic file format so all is about to integrate this format in sql and associated binary encoded format for the geometric part. there are no "obvious ways to do it yet", and several format available to use (WKB, SHAPE, ...). there are jdbc geographic access to can get inspired (ie: sqllite , .. )
